# 1.CREATE A 3X3X3 ARRAY WITH RANDOM VALUES

In [3]:
import numpy as np
random_array = np.random.rand(3, 3, 3)
print(random_array)

[[[0.16672849 0.05123141 0.4198135 ]
  [0.59871352 0.70144825 0.67232378]
  [0.10652629 0.75869116 0.0981197 ]]

 [[0.74376035 0.83287754 0.77740719]
  [0.3230267  0.58845093 0.74022141]
  [0.79072568 0.10652282 0.82841676]]

 [[0.06257719 0.95215153 0.28819355]
  [0.413721   0.51024539 0.76094649]
  [0.41373383 0.09677851 0.20382307]]]


# 2. Create a 5x5 matrix with values 1, 2, 3, and 4 just below the diagonal 

In [4]:
import numpy as np
matrix = np.zeros((5, 5))
for i in range(1, 5):
    matrix[i, i - 1] = i
print(matrix)

[[0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0.]
 [0. 2. 0. 0. 0.]
 [0. 0. 3. 0. 0.]
 [0. 0. 0. 4. 0.]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [7]:
import numpy as np
matrix = np.zeros((8, 8), dtype=int)
matrix[1::2, ::2] = 1
matrix[::2, 1::2] = 1
print(matrix)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 4.NORMALIZE A 5X5 RANDOM MATRIX

In [9]:
import numpy as np
matrix = np.random.rand(5, 5)
normalized_matrix = (matrix - np.min(matrix)) / (np.max(matrix) - np.min(matrix))
print("Matrix:")
print(matrix)
print("\nNormalized matrix:")
print(normalized_matrix)

Matrix:
[[0.43157923 0.01360807 0.66625248 0.52881288 0.26045061]
 [0.1904973  0.78333082 0.68080375 0.24504745 0.13490413]
 [0.16184969 0.29905703 0.58514808 0.30346081 0.56609485]
 [0.08811413 0.16363084 0.24357945 0.04993267 0.00262067]
 [0.56746205 0.56669722 0.82726032 0.22131739 0.6031054 ]]

Normalized matrix:
[[0.52017697 0.01332387 0.8047537  0.63808744 0.3126577 ]
 [0.22782876 0.94672885 0.8223993  0.29397905 0.16041364]
 [0.19308921 0.35947381 0.70640237 0.36481406 0.68329745]
 [0.10367371 0.19524911 0.29219887 0.05737293 0.        ]
 [0.68495539 0.68402792 1.         0.26520277 0.72817833]]


# 5.HOW TO FIND COMMON VALUES BETWEN TWO ARRAYS.

In [11]:
import numpy as np
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([31, 10, 5, 6, 7])
common_values = np.intersect1d(array1, array2)
print(common_values)

[5]


# 6.HOW TO GET THE DATES OF YESTERDAY,TODAY AND TOMORROW

In [12]:
import datetime
import numpy as np
today = datetime.date.today()
yesterday = today - datetime.timedelta(days=1)
tomorrow = today + datetime.timedelta(days=1)
date_array = np.array([yesterday, today, tomorrow])
print("Yesterday:", date_array[0])
print("Today:", date_array[1])
print("Tomorrow:", date_array[2])


Yesterday: 2023-09-20
Today: 2023-09-21
Tomorrow: 2023-09-22


# 7.CONSIDER TWO RANDOM ARRAY A AND B ,CHECK IF THEY ARE EQUAL.

In [13]:
import numpy as np
A = np.random.rand(5)
B = np.random.rand(5)
equal = np.array_equal(A, B)

if equal:
    print("Arrays A and B are equal.")
else:
    print("Arrays A and B are not equal.")

Arrays A and B are not equal.


# 8.CREATE A RANDOM VECTOR OF SIZE 10 AND REPLACE THE MAXIMUM VALUE BY 0

In [15]:
import numpy as np
random_vector = np.random.rand(10)
max_index = np.argmax(random_vector)
random_vector[max_index] = 0
print(random_vector)

[0.07022799 0.15847512 0.7861317  0.         0.00728065 0.20232745
 0.32302416 0.03726536 0.04704048 0.48679614]


# 9.HOW TO PRINT ALL THE VALUES OF AN ARRAY?

In [17]:
import numpy as np
my_array = np.array([11, 22, 33, 44, 55])
np.set_printoptions(threshold=np.inf)
print(my_array)


[11 22 33 44 55]


# 10.SUBTRACT THE MEAN OF EACH ROW OF A MATRIX

In [18]:
import numpy as np
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
row_means = np.mean(matrix, axis=1, keepdims=True)
result_matrix = matrix - row_means
print(result_matrix)

[[-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]]


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector ?

In [39]:
import numpy as np
given_vector = np.array([1, 2, 3, 4, 5])
index_vector = np.array([1, 3, 2, 1, 4, 3])
unique_indices = np.unique(index_vector)
a = np.isin(np.arange(len(given_vector)), unique_indices)
given_vector[a] += 1
print(given_vector)



[1 3 4 5 6]


# 12.HOW TO GET THE DIAGONAL OF DOT PRODUCT

In [20]:
import numpy as np
matrix_A = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])

matrix_B = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])
result = np.dot(matrix_A, matrix_B)
diagonal_elements = np.diag(result)
print(diagonal_elements)



[ 30  81 150]


# 13.HOW TO FIND THE MOST FREQUENT VALUE IN AN ARRAY.

In [21]:
x = np.random.randint(0,10,50)
x

array([6, 6, 5, 7, 1, 0, 0, 6, 9, 3, 4, 9, 9, 6, 3, 6, 8, 4, 6, 3, 6, 2,
       1, 5, 4, 5, 6, 2, 3, 4, 6, 3, 7, 5, 1, 3, 6, 9, 0, 7, 1, 3, 1, 1,
       8, 6, 8, 6, 3, 2])

In [25]:
import numpy as np
counts = np.bincount(x)
most_frequent_value = np.argmax(counts)
print("most frequent value:",most_frequent_value)

most frequent value: 6


# 14.HOW TO GET N LARGEST VALUES OF AN ARRAY

In [28]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6])
n_largest = 3
n_largest_values = np.partition(arr, n_largest)[n_largest:]
print("The", n_largest, "largest values:", n_largest_values)


The 3 largest values: [4 5 6]


# 15.HOW TO CREATE A RECORD OF ARRAY FROM A REGULAR ARRAY?

In [7]:
import numpy as np
regular_array = np.array([1,2,3])
record_array = np.rec.array(regular_array,dtype=[('my_column',int)])
print("record array:")
print(record_array)
print("my_column:",record_array.my_column)

record array:
[(1,) (2,) (3,)]
my_column: [1 2 3]


# 16.HOW TO SWAP TWO ROWS OF AN ARRAY?

In [32]:
import numpy as np
array = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])
array[2], array[1] = array[1], array[2]
print(array)


[[1 2 3]
 [4 5 6]
 [4 5 6]]


# 17. WRITE A PYTHON CODE TO RESHAPE THE NEXT DIMENSION OF NUMPY ARRAY .

In [34]:
x = np.array([[23, 34, 121],[23, 22, 67],[686, 434, 123]])
x

array([[ 23,  34, 121],
       [ 23,  22,  67],
       [686, 434, 123]])

In [35]:
reshape_array=np.reshape(x,(3,3))
print(reshape_array)

[[ 23  34 121]
 [ 23  22  67]
 [686 434 123]]
